<?php

namespace ContainerEmJ6Xls;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAfficherBackChargeControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SedKTZ2.App\Controller\AfficherBackChargeController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SedKTZ2.App\\Controller\\AfficherBackChargeController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chargeRepository' => ['privates', 'App\\Repository\\ChargeRepository', 'getChargeRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'chargeRepository' => 'App\\Repository\\ChargeRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\AfficherBackChargeController::delete()', $container);
    }
}
