<?php

namespace ContainerVcNeMh8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VDTX8XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VDT_x8X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'request' => ['privates', '.errored.LKS4sTv', NULL, 'Cannot determine controller argument for "App\\Controller\\MesCommandesController::index()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'em' => '?',
            'request' => '?',
        ]);

        if (isset($container->privates['.service_locator.VDT_x8X'])) {
            return $container->privates['.service_locator.VDT_x8X'];
        }

        return $container->privates['.service_locator.VDT_x8X'] = $instance;
    }
}
