<?php

namespace ContainerVcNeMh8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L15KSPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._l15KSP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminCommandeController::detail' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AdminCommandeController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AdminCommandeController::refuser' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AdminCommandeController::valider' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AdminDashboardController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\MarketplaceController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\MesCommandesController::detail' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\MesCommandesController::index' => ['privates', '.service_locator.VDT_x8X', 'get_ServiceLocator_VDTX8XService', true],
            'App\\Controller\\PanierController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\PanierController::modifierAjax' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\PanierController::valider' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.6DpIc9s', 'get_ServiceLocator_6DpIc9sService', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.6DpIc9s', 'get_ServiceLocator_6DpIc9sService', true],
            'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProduitController::new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminCommandeController:detail' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AdminCommandeController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AdminCommandeController:refuser' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AdminCommandeController:valider' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AdminDashboardController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\MarketplaceController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\MesCommandesController:detail' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\MesCommandesController:index' => ['privates', '.service_locator.VDT_x8X', 'get_ServiceLocator_VDTX8XService', true],
            'App\\Controller\\PanierController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\PanierController:modifierAjax' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\PanierController:valider' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.6DpIc9s', 'get_ServiceLocator_6DpIc9sService', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.6DpIc9s', 'get_ServiceLocator_6DpIc9sService', true],
            'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProduitController:new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminCommandeController::detail' => '?',
            'App\\Controller\\AdminCommandeController::index' => '?',
            'App\\Controller\\AdminCommandeController::refuser' => '?',
            'App\\Controller\\AdminCommandeController::valider' => '?',
            'App\\Controller\\AdminDashboardController::index' => '?',
            'App\\Controller\\MarketplaceController::index' => '?',
            'App\\Controller\\MesCommandesController::detail' => '?',
            'App\\Controller\\MesCommandesController::index' => '?',
            'App\\Controller\\PanierController::index' => '?',
            'App\\Controller\\PanierController::modifierAjax' => '?',
            'App\\Controller\\PanierController::valider' => '?',
            'App\\Controller\\ProduitController::delete' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::index' => '?',
            'App\\Controller\\ProduitController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminCommandeController:detail' => '?',
            'App\\Controller\\AdminCommandeController:index' => '?',
            'App\\Controller\\AdminCommandeController:refuser' => '?',
            'App\\Controller\\AdminCommandeController:valider' => '?',
            'App\\Controller\\AdminDashboardController:index' => '?',
            'App\\Controller\\MarketplaceController:index' => '?',
            'App\\Controller\\MesCommandesController:detail' => '?',
            'App\\Controller\\MesCommandesController:index' => '?',
            'App\\Controller\\PanierController:index' => '?',
            'App\\Controller\\PanierController:modifierAjax' => '?',
            'App\\Controller\\PanierController:valider' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:index' => '?',
            'App\\Controller\\ProduitController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator._l15KSP'])) {
            return $container->privates['.service_locator._l15KSP'];
        }

        return $container->privates['.service_locator._l15KSP'] = $instance;
    }
}
