# Enable CSRF protection for forms and security
framework:
    # Active la protection CSRF globale
    csrf_protection:
        enabled: true

    form:
        # Active la protection spécifique pour les formulaires
        csrf_protection:
            enabled: true