<?php

namespace ContainerIXgGXY2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CVIRQIrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cVIRQIr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cVIRQIr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utilisateur' => ['privates', '.errored..service_locator.cVIRQIr.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.cVIRQIr": it needs an instance of "App\\Entity\\Utilisateur" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'utilisateur' => 'App\\Entity\\Utilisateur',
            'entityManager' => '?',
        ]);
    }
}
