<?php

namespace ContainerIxUoDQm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IY8uJH..App\Entity\Reclamations' shared service.
     *
     * @return \App\Entity\Reclamations
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.IY8uJH.": it needs an instance of "App\\Entity\\Reclamations" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
