<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Franchises extends \App\Entity\Franchises implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'actif' => [parent::class, 'actif', null, 16],
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'alerteiass' => [parent::class, 'alerteiass', null, 16],
        "\0".parent::class."\0".'bilans' => [parent::class, 'bilans', null, 16],
        "\0".parent::class."\0".'budget_previsionnels' => [parent::class, 'budget_previsionnels', null, 16],
        "\0".parent::class."\0".'charges' => [parent::class, 'charges', null, 16],
        "\0".parent::class."\0".'commandes' => [parent::class, 'commandes', null, 16],
        "\0".parent::class."\0".'date_creation' => [parent::class, 'date_creation', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'fournisseurs' => [parent::class, 'fournisseurs', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'prets' => [parent::class, 'prets', null, 16],
        "\0".parent::class."\0".'reclamationss' => [parent::class, 'reclamationss', null, 16],
        "\0".parent::class."\0".'solde_actuel' => [parent::class, 'solde_actuel', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        "\0".parent::class."\0".'transactions' => [parent::class, 'transactions', null, 16],
        "\0".parent::class."\0".'utilisateurs' => [parent::class, 'utilisateurs', null, 16],
        'actif' => [parent::class, 'actif', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'alerteiass' => [parent::class, 'alerteiass', null, 16],
        'bilans' => [parent::class, 'bilans', null, 16],
        'budget_previsionnels' => [parent::class, 'budget_previsionnels', null, 16],
        'charges' => [parent::class, 'charges', null, 16],
        'commandes' => [parent::class, 'commandes', null, 16],
        'date_creation' => [parent::class, 'date_creation', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'fournisseurs' => [parent::class, 'fournisseurs', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'prets' => [parent::class, 'prets', null, 16],
        'reclamationss' => [parent::class, 'reclamationss', null, 16],
        'solde_actuel' => [parent::class, 'solde_actuel', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
        'transactions' => [parent::class, 'transactions', null, 16],
        'utilisateurs' => [parent::class, 'utilisateurs', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
