<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commande extends \App\Entity\Commande implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'date_creation' => [parent::class, 'date_creation', null, 16],
        "\0".parent::class."\0".'franchise_id' => [parent::class, 'franchise_id', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'ligne_commandes' => [parent::class, 'ligne_commandes', null, 16],
        "\0".parent::class."\0".'montant_total' => [parent::class, 'montant_total', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        'date_creation' => [parent::class, 'date_creation', null, 16],
        'franchise_id' => [parent::class, 'franchise_id', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'ligne_commandes' => [parent::class, 'ligne_commandes', null, 16],
        'montant_total' => [parent::class, 'montant_total', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
