<?php

namespace ContainerIEgyoEq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_We0L8dpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.we0L8dp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.we0L8dp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entreprise' => ['privates', '.errored..service_locator.we0L8dp.App\\Entity\\Franchises', NULL, 'Cannot autowire service ".service_locator.we0L8dp": it needs an instance of "App\\Entity\\Franchises" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'entreprise' => 'App\\Entity\\Franchises',
            'entityManager' => '?',
        ]);
    }
}
