<?php

namespace ContainerIEgyoEq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminUserControllereditInlineService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cVIRQIr.App\Controller\AdminUserController::editInline()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cVIRQIr.App\\Controller\\AdminUserController::editInline()'] = ($container->privates['.service_locator.cVIRQIr'] ?? $container->load('get_ServiceLocator_CVIRQIrService'))->withContext('App\\Controller\\AdminUserController::editInline()', $container);
    }
}
