<?php

namespace ContainerIEgyoEq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminEntrepriseControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.we0L8dp.App\Controller\AdminEntrepriseController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.we0L8dp.App\\Controller\\AdminEntrepriseController::delete()'] = ($container->privates['.service_locator.we0L8dp'] ?? $container->load('get_ServiceLocator_We0L8dpService'))->withContext('App\\Controller\\AdminEntrepriseController::delete()', $container);
    }
}
