<?php

namespace ContainerIEgyoEq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFranchisesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.we0L8dp.App\Entity\Franchises' shared service.
     *
     * @return \App\Entity\Franchises
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.we0L8dp": it needs an instance of "App\\Entity\\Franchises" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
