<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxQzub3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxQzub3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVxQzub3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVxQzub3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVxQzub3\App_KernelDevDebugContainer([
    'container.build_hash' => 'VxQzub3',
    'container.build_id' => '22740f30',
    'container.build_time' => 1775465826,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxQzub3');
