<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEmJ6Xls\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEmJ6Xls/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEmJ6Xls.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEmJ6Xls\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEmJ6Xls\App_KernelDevDebugContainer([
    'container.build_hash' => 'EmJ6Xls',
    'container.build_id' => '34efbdb7',
    'container.build_time' => 1775315652,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEmJ6Xls');
