<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIixRrUO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIixRrUO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIixRrUO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIixRrUO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIixRrUO\App_KernelDevDebugContainer([
    'container.build_hash' => 'IixRrUO',
    'container.build_id' => '7752fb61',
    'container.build_time' => 1775343511,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIixRrUO');
