<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_admin_entreprise' => [[], ['_controller' => 'App\\Controller\\AdminEntrepriseController::index'], [], [['text', '/admin/entreprise']], [], [], []],
    'app_admin_reclamation' => [[], ['_controller' => 'App\\Controller\\AdminReclamationController::index'], [], [['text', '/admin/reclamation']], [], [], []],
    'app_admin_user' => [[], ['_controller' => 'App\\Controller\\AdminUserController::index'], [], [['text', '/admin/user']], [], [], []],
    'app_admin_user_new' => [[], ['_controller' => 'App\\Controller\\AdminUserController::new'], [], [['text', '/admin/user/new']], [], [], []],
    'reclamation_index' => [[], ['_controller' => 'App\\Controller\\ReclamationController::index'], [], [['text', '/reclamations/']], [], [], []],
    'reclamation_new' => [[], ['_controller' => 'App\\Controller\\ReclamationController::new'], [], [['text', '/reclamations/new']], [], [], []],
    'reclamation_delete' => [['id'], ['_controller' => 'App\\Controller\\ReclamationController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/reclamations']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_forgot_password' => [[], ['_controller' => 'App\\Controller\\SecurityController::forgotPassword'], [], [['text', '/forgot-password']], [], [], []],
    'App\Controller\AdminEntrepriseController::index' => [[], ['_controller' => 'App\\Controller\\AdminEntrepriseController::index'], [], [['text', '/admin/entreprise']], [], [], []],
    'App\Controller\AdminReclamationController::index' => [[], ['_controller' => 'App\\Controller\\AdminReclamationController::index'], [], [['text', '/admin/reclamation']], [], [], []],
    'App\Controller\AdminUserController::index' => [[], ['_controller' => 'App\\Controller\\AdminUserController::index'], [], [['text', '/admin/user']], [], [], []],
    'App\Controller\AdminUserController::new' => [[], ['_controller' => 'App\\Controller\\AdminUserController::new'], [], [['text', '/admin/user/new']], [], [], []],
    'App\Controller\ReclamationController::index' => [[], ['_controller' => 'App\\Controller\\ReclamationController::index'], [], [['text', '/reclamations/']], [], [], []],
    'App\Controller\ReclamationController::new' => [[], ['_controller' => 'App\\Controller\\ReclamationController::new'], [], [['text', '/reclamations/new']], [], [], []],
    'App\Controller\ReclamationController::delete' => [['id'], ['_controller' => 'App\\Controller\\ReclamationController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/reclamations']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\SecurityController::forgotPassword' => [[], ['_controller' => 'App\\Controller\\SecurityController::forgotPassword'], [], [['text', '/forgot-password']], [], [], []],
];
