<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_admin_entreprise' => [[], ['_controller' => 'App\\Controller\\AdminEntrepriseController::index'], [], [['text', '/admin/entreprise']], [], [], []],
    'app_admin_entreprise_edit_inline' => [['id'], ['_controller' => 'App\\Controller\\AdminEntrepriseController::editInline'], [], [['text', '/edit-inline'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/entreprise']], [], [], []],
    'app_admin_entreprise_delete' => [['id'], ['_controller' => 'App\\Controller\\AdminEntrepriseController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/entreprise']], [], [], []],
    'app_admin_user' => [[], ['_controller' => 'App\\Controller\\AdminUserController::index'], [], [['text', '/admin/user']], [], [], []],
    'app_admin_user_edit_inline' => [['id'], ['_controller' => 'App\\Controller\\AdminUserController::editInline'], [], [['text', '/edit-inline'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/user']], [], [], []],
    'app_admin_user_delete' => [['id'], ['_controller' => 'App\\Controller\\AdminUserController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/user']], [], [], []],
    'app_admin_user_new' => [[], ['_controller' => 'App\\Controller\\AdminUserController::new'], [], [['text', '/admin/user/new']], [], [], []],
    'app_front_home' => [[], ['_controller' => 'App\\Controller\\FrontController::index'], [], [['text', '/front']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\SecurityController::home'], [], [['text', '/']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_forgot_password' => [[], ['_controller' => 'App\\Controller\\SecurityController::forgotPassword'], [], [['text', '/forgot-password']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], [], []],
    'App\Controller\AdminEntrepriseController::index' => [[], ['_controller' => 'App\\Controller\\AdminEntrepriseController::index'], [], [['text', '/admin/entreprise']], [], [], []],
    'App\Controller\AdminEntrepriseController::editInline' => [['id'], ['_controller' => 'App\\Controller\\AdminEntrepriseController::editInline'], [], [['text', '/edit-inline'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/entreprise']], [], [], []],
    'App\Controller\AdminEntrepriseController::delete' => [['id'], ['_controller' => 'App\\Controller\\AdminEntrepriseController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/entreprise']], [], [], []],
    'App\Controller\AdminUserController::index' => [[], ['_controller' => 'App\\Controller\\AdminUserController::index'], [], [['text', '/admin/user']], [], [], []],
    'App\Controller\AdminUserController::editInline' => [['id'], ['_controller' => 'App\\Controller\\AdminUserController::editInline'], [], [['text', '/edit-inline'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/user']], [], [], []],
    'App\Controller\AdminUserController::delete' => [['id'], ['_controller' => 'App\\Controller\\AdminUserController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/user']], [], [], []],
    'App\Controller\AdminUserController::new' => [[], ['_controller' => 'App\\Controller\\AdminUserController::new'], [], [['text', '/admin/user/new']], [], [], []],
    'App\Controller\FrontController::index' => [[], ['_controller' => 'App\\Controller\\FrontController::index'], [], [['text', '/front']], [], [], []],
    'App\Controller\SecurityController::home' => [[], ['_controller' => 'App\\Controller\\SecurityController::home'], [], [['text', '/']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\SecurityController::forgotPassword' => [[], ['_controller' => 'App\\Controller\\SecurityController::forgotPassword'], [], [['text', '/forgot-password']], [], [], []],
];
