<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_admin_reclamation' => [[], ['_controller' => 'App\\Controller\\AdminReclamationController::index'], [], [['text', '/admin/reclamation']], [], [], []],
    'app_afficher_back_charge' => [[], ['_controller' => 'App\\Controller\\AfficherBackChargeController::index'], [], [['text', '/afficher_back_charge']], [], [], []],
    'app_charge_delete' => [['id'], ['_controller' => 'App\\Controller\\AfficherBackChargeController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/afficher_back_charge/delete']], [], [], []],
    'app_ajouter_charge' => [[], ['_controller' => 'App\\Controller\\AjouterChargeController::index'], [], [['text', '/ajouter_charge']], [], [], []],
    'reclamation_index' => [[], ['_controller' => 'App\\Controller\\ReclamationController::index'], [], [['text', '/reclamations/']], [], [], []],
    'reclamation_new' => [[], ['_controller' => 'App\\Controller\\ReclamationController::new'], [], [['text', '/reclamations/new']], [], [], []],
    'reclamation_delete' => [['id'], ['_controller' => 'App\\Controller\\ReclamationController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/reclamations']], [], [], []],
    'App\Controller\AdminReclamationController::index' => [[], ['_controller' => 'App\\Controller\\AdminReclamationController::index'], [], [['text', '/admin/reclamation']], [], [], []],
    'App\Controller\AfficherBackChargeController::index' => [[], ['_controller' => 'App\\Controller\\AfficherBackChargeController::index'], [], [['text', '/afficher_back_charge']], [], [], []],
    'App\Controller\AfficherBackChargeController::delete' => [['id'], ['_controller' => 'App\\Controller\\AfficherBackChargeController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/afficher_back_charge/delete']], [], [], []],
    'App\Controller\AjouterChargeController::index' => [[], ['_controller' => 'App\\Controller\\AjouterChargeController::index'], [], [['text', '/ajouter_charge']], [], [], []],
    'App\Controller\ReclamationController::index' => [[], ['_controller' => 'App\\Controller\\ReclamationController::index'], [], [['text', '/reclamations/']], [], [], []],
    'App\Controller\ReclamationController::new' => [[], ['_controller' => 'App\\Controller\\ReclamationController::new'], [], [['text', '/reclamations/new']], [], [], []],
    'App\Controller\ReclamationController::delete' => [['id'], ['_controller' => 'App\\Controller\\ReclamationController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/reclamations']], [], [], []],
];
