<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HmdVCLIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HmdVCLI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HmdVCLI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bilan' => ['privates', '.errored..service_locator.HmdVCLI.App\\Entity\\Bilan', NULL, 'Cannot autowire service ".service_locator.HmdVCLI": it needs an instance of "App\\Entity\\Bilan" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'bilan' => 'App\\Entity\\Bilan',
            'entityManager' => '?',
        ]);
    }
}
