<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gp2BU3jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gp2BU3j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gp2BU3j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'alerte' => ['privates', '.errored..service_locator.Gp2BU3j.App\\Entity\\Alerteias', NULL, 'Cannot autowire service ".service_locator.Gp2BU3j": it needs an instance of "App\\Entity\\Alerteias" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'alerte' => 'App\\Entity\\Alerteias',
        ]);
    }
}
