<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IY8uJH_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IY8uJH.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IY8uJH.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reclamation' => ['privates', '.errored..service_locator.IY8uJH..App\\Entity\\Reclamations', NULL, 'Cannot autowire service ".service_locator.IY8uJH.": it needs an instance of "App\\Entity\\Reclamations" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'reclamation' => 'App\\Entity\\Reclamations',
        ]);
    }
}
