<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlerteiasService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Gp2BU3j.App\Entity\Alerteias' shared service.
     *
     * @return \App\Entity\Alerteias
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Gp2BU3j": it needs an instance of "App\\Entity\\Alerteias" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
