<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminReclamationControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IY8uJH..App\Controller\AdminReclamationController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IY8uJH..App\\Controller\\AdminReclamationController::delete()'] = ($container->privates['.service_locator.IY8uJH.'] ?? $container->load('get_ServiceLocator_IY8uJH_Service'))->withContext('App\\Controller\\AdminReclamationController::delete()', $container);
    }
}
