<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAfficherFrontChargeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._b_k9zL.App\Controller\AfficherFrontChargeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._b_k9zL.App\\Controller\\AfficherFrontChargeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ChargeRepository', 'getChargeRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ChargeRepository',
        ]))->withContext('App\\Controller\\AfficherFrontChargeController::index()', $container);
    }
}
