<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAfficherBackChargeControllerinlineEditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nzqdLkv.App\Controller\AfficherBackChargeController::inlineEdit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nzqdLkv.App\\Controller\\AfficherBackChargeController::inlineEdit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'charge' => ['privates', '.errored..service_locator.nzqdLkv.App\\Entity\\Charge', NULL, 'Cannot autowire service ".service_locator.nzqdLkv": it needs an instance of "App\\Entity\\Charge" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'chargeRepository' => ['privates', 'App\\Repository\\ChargeRepository', 'getChargeRepositoryService', true],
        ], [
            'charge' => 'App\\Entity\\Charge',
            'entityManager' => '?',
            'chargeRepository' => 'App\\Repository\\ChargeRepository',
        ]))->withContext('App\\Controller\\AfficherBackChargeController::inlineEdit()', $container);
    }
}
