<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlerteIAControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gp2BU3j.App\Controller\AlerteIAController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gp2BU3j.App\\Controller\\AlerteIAController::delete()'] = ($container->privates['.service_locator.Gp2BU3j'] ?? $container->load('get_ServiceLocator_Gp2BU3jService'))->withContext('App\\Controller\\AlerteIAController::delete()', $container);
    }
}
