<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAjouterChargeControllermodifierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mQkJDzl.App\Controller\AjouterChargeController::modifier()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mQkJDzl.App\\Controller\\AjouterChargeController::modifier()'] = ($container->privates['.service_locator.mQkJDzl'] ?? $container->load('get_ServiceLocator_MQkJDzlService'))->withContext('App\\Controller\\AjouterChargeController::modifier()', $container);
    }
}
