<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBilanControllerdeleteAjaxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HmdVCLI.App\Controller\BilanController::deleteAjax()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HmdVCLI.App\\Controller\\BilanController::deleteAjax()'] = ($container->privates['.service_locator.HmdVCLI'] ?? $container->load('get_ServiceLocator_HmdVCLIService'))->withContext('App\\Controller\\BilanController::deleteAjax()', $container);
    }
}
