<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBudgetControllerdeleteAjaxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Nk.7tKq.App\Controller\BudgetController::deleteAjax()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Nk.7tKq.App\\Controller\\BudgetController::deleteAjax()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'budget' => ['privates', '.errored..service_locator.Nk.7tKq.App\\Entity\\Budget_previsionnel', NULL, 'Cannot autowire service ".service_locator.Nk.7tKq": it needs an instance of "App\\Entity\\Budget_previsionnel" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'budget' => 'App\\Entity\\Budget_previsionnel',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\BudgetController::deleteAjax()', $container);
    }
}
