<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBudgetControllereditAjaxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QDN3581.App\Controller\BudgetController::editAjax()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'budget' => ['privates', '.errored..service_locator.QDN3581.App\\Entity\\Budget_previsionnel', NULL, 'Cannot autowire service ".service_locator.QDN3581": it needs an instance of "App\\Entity\\Budget_previsionnel" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'budget' => 'App\\Entity\\Budget_previsionnel',
            'entityManager' => '?',
            'validator' => '?',
        ]))->withContext('App\\Controller\\BudgetController::editAjax()', $container);

        if (isset($container->privates['.service_locator.QDN3581.App\\Controller\\BudgetController::editAjax()'])) {
            return $container->privates['.service_locator.QDN3581.App\\Controller\\BudgetController::editAjax()'];
        }

        return $container->privates['.service_locator.QDN3581.App\\Controller\\BudgetController::editAjax()'] = $instance;
    }
}
