<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBudgetPrevisionnelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Nk.7tKq.App\Entity\Budget_previsionnel' shared service.
     *
     * @return \App\Entity\Budget_previsionnel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Nk.7tKq": it needs an instance of "App\\Entity\\Budget_previsionnel" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
