<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCharge2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nzqdLkv.App\Entity\Charge' shared service.
     *
     * @return \App\Entity\Charge
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.nzqdLkv": it needs an instance of "App\\Entity\\Charge" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
