<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..oI3_l2.App\Entity\Transaction' shared service.
     *
     * @return \App\Entity\Transaction
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..oI3_l2": it needs an instance of "App\\Entity\\Transaction" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
