<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..oI3_l2.App\Controller\TransactionController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transaction' => ['privates', '.errored..service_locator..oI3_l2.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator..oI3_l2": it needs an instance of "App\\Entity\\Transaction" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'transaction' => 'App\\Entity\\Transaction',
            'entityManager' => '?',
            'validator' => '?',
        ]))->withContext('App\\Controller\\TransactionController::edit()', $container);

        if (isset($container->privates['.service_locator..oI3_l2.App\\Controller\\TransactionController::edit()'])) {
            return $container->privates['.service_locator..oI3_l2.App\\Controller\\TransactionController::edit()'];
        }

        return $container->privates['.service_locator..oI3_l2.App\\Controller\\TransactionController::edit()'] = $instance;
    }
}
