<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z_yDV7H.App\Controller\TransactionController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z_yDV7H.App\\Controller\\TransactionController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transaction' => ['privates', '.errored..service_locator.z_yDV7H.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.z_yDV7H": it needs an instance of "App\\Entity\\Transaction" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'transaction' => 'App\\Entity\\Transaction',
        ]))->withContext('App\\Controller\\TransactionController::show()', $container);
    }
}
