<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z3FtZ1U.App\Controller\TransactionController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z3FtZ1U.App\\Controller\\TransactionController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transaction' => ['privates', '.errored..service_locator.z3FtZ1U.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.z3FtZ1U": it needs an instance of "App\\Entity\\Transaction" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'transaction' => 'App\\Entity\\Transaction',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\TransactionController::delete()', $container);
    }
}
