<?php

namespace ContainerBJgLHCC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionControllerhistoriqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._RrU5AO.App\Controller\TransactionController::historique()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._RrU5AO.App\\Controller\\TransactionController::historique()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transactionRepo' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'transactionRepo' => 'App\\Repository\\TransactionRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\TransactionController::historique()', $container);
    }
}
